module.exports={
    persons:[
                {id:1,nume:"Popp Roxana"},
                {id:2,nume:"Mot Carina"},			
                {id:3,nume:"Popescu Ion"}],
    abonaments:[{
                    id:1,
                    tip_abonament:"Netflix",
                    data_expirare:'2020-04-15',
                    tarif_lunar:50,
                    imagine:"netflix.png",
                    activ:true,
                    person_id : 1},
                    {id:2,
                    tip_abonament:"HBO GO",
                    data_expirare:'2020-04-10',
                    tarif_lunar:30,
                    imagine:"hbo.png",
                    activ:false,
                    person_id : 2},
                    {id:3,
                    tip_abonament:"Antena Play",
                    data_expirare:'2020-05-20',
                    tarif_lunar:20,
                    imagine:"antena.png",
                    activ:true,
                    person_id : 2},
                    {id:4,
                    tip_abonament:"HBO GO",
                    data_expirare:'2020-06-06',
                    tarif_lunar:30,
                    imagine:"hbo.png",
                    activ:true,
                    person_id : 3},
                    {id:5,
                    tip_abonament:"Netflix",
                    imagine:"antena.png",
                    tarif_lunar:70,
                    data_expirare:'2020-04-25',
                    activ:false,
                    person_id : 1}],
                                      
    }